create database customer_behavior;
use customer_behavior;
select * from customer limit 20;
-- update customer 
-- set purchase_amount=

-- Q1. What is the total revenue generated by male and female customers?
select gender,sum(purcase_amount) as revenue
from customer
group by gender;
-- Q2. Which customers used a discount and spent more than the average purchase amount?
select customer_id,purcase_amount
from customer
where discount_applied = 'Yes' and purcase_amount > (
      select avg(purcase_amount)
     from customer
  );
-- Q3. What are the top 5 products with the highest average review ratings?
select item_purchased ,round(avg(review_rating),2) as 'Average Product Rating'
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


-- Q4. How do average purchase amounts compare between Standard and Express shipping?
select shipping_type,avg(purcase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more than non-subscribers in terms of average spend and total revenue?
select * from customer limit 5;
select subscription_status,
count(customer_id) as total_customers,round(avg(purcase_amount),2) as Average_spend,sum(purcase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue,Average_spend desc;
-- Q6. Which 5 products have the highest percentage of purchases made with discounts applied?
SELECT item_purchased,
       ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*), 2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. How many customers belong to the New, Returning, and Loyal customer segments based on previous purchases?
select * from customer limit 5;
with customer_type as(
select customer_id,previous_purchases,
case 
	when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)
select customer_segment,count(*) as 'Number of Customers'
from customer_type
group by customer_segment;
-- Q8. What are the top 3 most purchased products within each category?
select * from customer limit 3;
with top_customer as(
select category,item_purchased,count(customer_id) as total_orders,
row_number()over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from top_customer
where item_rank<=3;

-- Q9. Are repeat buyers (customers with more than 5 previous purchases) more likely to be subscribed?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group,
sum(purcase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;